### ISSUE TITLE
Syntax & Checklist

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/log-command#2]
**Syntax**
- [ ] `ee log` => displays help and exit
- [ ] `ee log show --cli` => displays easyengine's own logs 
- [ ] `ee log show --global` => displays all logs including all sites, all services and cli
- [ ] `ee log show --n=<line-count>` => start with last number of <line-count>. Default is 10. This is passed to `tail` command internally as `tail -n <line-count>`

**Site Syntax**
- [ ] `ee log show <sitename>` => displays nginx + php + wp (if applicable) logs for a site
- [ ] `ee log show <sitename> --all` => displays all local logs, including service logs
- [ ] `ee log show <sitename> --nginx` => displays nginx logs for a site
- [ ] `ee log show <sitename> --php` => displays php logs for a site
- [ ] `ee log show <sitename> --wp` => displays wp dbeug log for a site
- [ ] `ee log show <sitename> --services` => displays service logs **only** for a site
- [ ] `ee log show <sitename> --mysql` => displays mysql logs for a site
- [ ] `ee log show <sitename> --redis` => displays redis logs for a site
- [ ] `ee log show <sitename> --access` => displays nginx & php access logs for a site
- [ ] `ee log show <sitename> --error` => displays nginx & php error logs for a site

**Service Syntax**
- [ ] `ee log show --services` => displays service logs **only** for all global services
- [ ] `ee log show --services=<service-name>` => displays service logs **only** for all global service whose name is specified <service-name>

**Extra checklist**
- [ ] Service related flags will display an INFO message saying "example.com uses the global container for X so logs may have additional messages from other sites".
- [ ] Multiple logs flag can be specified e.g. `--nginx --php`. These will do UNION of all logs files associated with each flag.
- [ ] All `show` commands will have `ee log path` command which will display only log file path names rather than actual logs.
